### List all models

GET https://api.getimg.ai/v1/models
accept: application/json
Authorization: Bearer {{getimag-api-key}}

### Essential V2 text to image

POST https://api.getimg.ai/v1/essential-v2/text-to-image
accept: application/json
content-type: application/json
Authorization: Bearer {{getimag-api-key}}

{
    "prompt": "cute dwarf in a beautiful village created at the foot of a grand mountain"
}

### Stable Diffusion XL text to image

POST https://api.getimg.ai/v1/stable-diffusion-xl/text-to-image
accept: application/json
content-type: application/json
Authorization: Bearer {{getimag-api-key}}

{
    "prompt": "cute dwarf in a beautiful village created at the foot of a grand mountain"
}

### Stable Diffusion XL imnage to image

POST https://api.getimg.ai/v1/stable-diffusion-xl/image-to-image
accept: application/json
content-type: application/json
Authorization: Bearer {{getimag-api-key}}

{
    "prompt": "make the sword real",
    "image": "base64 encoded image"
}

### Stable Diffusion XL inpainting

POST https://api.getimg.ai/v1/stable-diffusion-xl/inpaint
accept: application/json
content-type: application/json
Authorization: Bearer {{getimag-api-key}}

{
    "prompt": "give the dwarf ten dwarf friends",
    "image": "base64 encoded image",
    "mask_image": "base64 encoded masking image"
}
